<?php
/*
 * Advanced Custom Fields configuration
 */

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_churches-fields',
		'title' => 'Churches Fields',
		'fields' => array (
			array (
				'key' => 'field_548a5bce41720',
				'label' => 'Doctrine Heading',
				'name' => 'doctrine_heading',
				'type' => 'text',
				'default_value' => 'A Primer',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_535f265bed1c9',
				'label' => 'Doctrine Primer',
				'name' => 'doctrine_primer',
				'type' => 'wysiwyg',
				'required' => 1,
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_69de5c1e435fb',
				'label' => 'Doctrine Button',
				'name' => 'doctrine_button',
				'type' => 'text',
				'default_value' => 'Download our full doctrine',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_535f26ad07cb7',
				'label' => 'Full Doctrine File',
				'name' => 'full_doctrine',
				'type' => 'file',
				'required' => 1,
				'save_format' => 'id',
				'library' => 'uploadedTo',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '9',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'featured_image',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_event-fields',
		'title' => 'Event Fields',
		'fields' => array (
			array (
				'key' => 'field_537456cfe162a',
				'label' => 'Dates',
				'name' => 'dates',
				'type' => 'text',
				'instructions' => 'Text description of the event\'s schedule',
				'required' => 1,
				'default_value' => 'TBA',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_537457736d700',
				'label' => 'Time',
				'name' => 'time',
				'type' => 'text',
				'instructions' => 'Text description of the event\'s start time',
				'default_value' => 'TBA',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_537457af43730',
				'label' => 'Location',
				'name' => 'location',
				'type' => 'text',
				'instructions' => 'The event\'s physical location.	May be omitted if already specified in the title.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53adf9859d306',
				'label' => 'Cost',
				'name' => 'cost',
				'type' => 'text',
				'instructions' => 'Cost of the event (ex: $59.99)',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53adf93fc1fb3',
				'label' => 'Register By',
				'name' => 'register_by',
				'type' => 'text',
				'instructions' => 'Specify the registration deadline',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53adf43fb0d46',
				'label' => 'Sign Up Link Text',
				'name' => 'sign_up_link_text',
				'type' => 'text',
				'instructions' => 'The signup form link\'s text',
				'default_value' => 'Sign up for this trip',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53746465423a7',
				'label' => 'Sign Up Form URL',
				'name' => 'sign_up_form_url',
				'type' => 'text',
				'instructions' => 'Link to an external sign up form',
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53adf4ace5727',
				'label' => 'Giving Link Text',
				'name' => 'giving_link_text',
				'type' => 'text',
				'instructions' => 'The giving form link\'s text',
				'default_value' => 'Give to a team member',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53adc2df09ea4',
				'label' => 'Giving Form URL',
				'name' => 'giving_form_url',
				'type' => 'text',
				'instructions' => 'Link to an external giving form',
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_event-visibility',
		'title' => 'Event Visibility',
		'fields' => array (
			array (
				'key' => 'field_5374599390abf',
				'label' => 'Pull Down Date',
				'name' => 'expiration',
				'type' => 'date_picker',
				'instructions' => 'Published events will remain visible until their pull down date is reached',
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_hear-the-cry-fields',
		'title' => 'Hear the Cry Fields',
		'fields' => array (
			array (
				'key' => 'field_5390113abe10d',
				'label' => 'Events Heading',
				'name' => 'events_heading',
				'type' => 'text',
				'required' => 1,
				'default_value' => 'Upcoming Trips',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '94',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '92',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_music-release-fields',
		'title' => 'Music Release Fields',
		'fields' => array (
			array (
				'key' => 'field_535f633250732',
				'label' => 'Album Art',
				'name' => 'album_art',
				'type' => 'image',
				'save_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_537b0fe5c5a25',
				'label' => 'More Info',
				'name' => 'more_info',
				'type' => 'wysiwyg',
				'instructions' => 'Short sentence, a link or set of links',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_537d7eff6f8ee',
				'label' => 'Learn More Link',
				'name' => 'itunes_url',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_537d7f0d38e01',
				'label' => 'Amazon URL',
				'name' => 'amazon_url',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'music_release',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'featured_image',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_page-fields',
		'title' => 'Page Fields',
		'fields' => array (
			array (
				'key' => 'field_539949c5a6b52',
				'label' => 'Tile Image',
				'name' => 'tile_image',
				'type' => 'image',
				'instructions' => 'The tile for this page in a grid-style navigation menu',
				'save_format' => 'id',
				'preview_size' => 'menu-tile',
				'library' => 'all',
			),
			array (
				'key' => 'field_537f17a2b86f5',
				'label' => 'Foreground',
				'name' => 'foreground',
				'type' => 'radio',
				'choices' => array (
					'white' => 'White',
					'black' => 'Black',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'white',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_535f156f5a80a',
				'label' => 'Vibe Banner',
				'name' => 'vibe_banner',
				'type' => 'image',
				'instructions' => 'This is the image background behind the logo and nav bar.',
				'save_format' => 'id',
				'preview_size' => 'vibe-banner',
				'library' => 'all',
			),
			array (
				'key' => 'field_535f15a50ded0',
				'label' => 'Hero Graphic',
				'name' => 'hero_graphic',
				'type' => 'image',
				'instructions' => 'This image fills the top of the page, behind text or a video.',
				'save_format' => 'id',
				'preview_size' => 'hero-film',
				'library' => 'all',
			),
			array (
				'key' => 'field_535f16009ae0f',
				'label' => 'Hero Phrase',
				'name' => 'hero_phrase',
				'type' => 'text',
				'instructions' => 'Hero phrase displayed above the Hero Graphic.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53adfdbedfe45',
				'label' => 'Hero Font Size',
				'name' => 'hero_font_size',
				'type' => 'number',
				'instructions' => 'Tweak hero text font size (in px) in order to optimize where it wraps.	Default is 60px.	Won\'t affect mobile.',
				'default_value' => '',
				'placeholder' => 60,
				'prepend' => '',
				'append' => '',
				'min' => 40,
				'max' => 70,
				'step' => '',
			),
			array (
				'key' => 'field_535f16346b64b',
				'label' => 'Vimeo ID',
				'name' => 'vimeo_id',
				'type' => 'text',
				'instructions' => 'The hero video\'s id number on Vimeo',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 12,
			),
			array (
				'key' => 'field_5390e9b4f7c50',
				'label' => 'Watch Button Text',
				'name' => 'watch_button_text',
				'type' => 'text',
				'instructions' => 'Text for the button used to launch embedded video',
				'default_value' => 'Watch this film',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 40,
			),
			array (
				'key' => 'field_5399171c423aa',
				'label' => 'Darken Header',
				'name' => 'darken_header',
				'type' => 'true_false',
				'message' => 'Slightly darken the hero graphic or vibe banner',
				'default_value' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'ministry',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'featured_image',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_post-tag-fields',
		'title' => 'Post Tag Fields',
		'fields' => array (
			array (
				'key' => 'field_537f2f53d36d1',
				'label' => 'Location Tag',
				'name' => 'location_tag',
				'type' => 'true_false',
				'message' => 'Tag represents a local church',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'post_tag',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
